apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-a5ot
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-etnh-tenant/status-quarkus-io/statusquarkusio-a5ot@sha256:42936a59f03f6edc8d854b8674189f31a4fa6ca2984798d3312049dbfdcebb35
        name: my-java-quarkus
        resources: {}
status: {}
